### ISSUE TITLE
[1.12.2 - Suggestion] Separate Shrug Chance between Player & Mob?

### ISSUE THREAD

**Issue by SonicX8000** [michelegargiulo/ShrugItOff#2]
Hope I can explain this well.

I think currently the Base Value for both the Old & new Formulas are shared for both Players & Mobs. I wonder if it's possible to separate that so Players & Mobs have their own Base & Max Values. For example...

Players could have a Old Formula Base Value of 0.1 along with the cap at 0.8 and New Formula Base Value at 10.0
Mobs could have a Old Formula Base Value of 10.0 along with the cap at 0.95 and New Formula Base Value at 50.0

There could also be an option to have either the Player or the Mob use the Old/New Formulas Separately, if one wanted to do that.

As to why I mention this, this is due to some mods that may add in items that have higher base damage or due to mobs lacking Toughness since most don't wear any armor so one may want to have mobs get a bit of a buff in toughness just to be able to shrug off damage.

P.S.
For the `logChances` & `logDamageSources` configs, could there be an option to have those only show in the console log instead of it being in the chat?

**Comment by michelegargiulo** [comment]
Implemented in version 1.0.0. Grab it from Modrinth/Curseforge, file should be approved on both
